/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

// A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
// This line has been manually overridden over the Swagger generated code to fix an unmarshalling bug.
// See https://groups.google.com/d/msg/strava-api/0EBIhSSsAws/LBkVdOgrCQAJ
type LatLng []float32
